### ISSUE TITLE
Restore original branch if possible.

### ISSUE THREAD

**Issue by charlesmchen** [floatplane/git_pr#33]
It’d be nice if git_pr left you on the same branch where you were when you invoked it.

ie. i’m on `feature/a` and I perform `git pr merge 123` (PR 123 corresponds to feature/a).

`git pr` fails, ie.:

```
Local branch 'feature/syncPageAttributes' differs from remote branch 'charlesmchen/feature/syncPageAttributes'. Please reconcile before continuing.
```

the temptation is to git push -f since you think you are still on feature/a.

I always have to catch myself.

**Comment by floatplane** [comment]
@charlesmchen fixed! I should have done this long ago.

I'll push the new version out widely after I live with it for a while, but if you're feeling experimental you can run `sudo gem install --pre git_pr`. "--pre" is short for pre-release.

**Comment by charlesmchen** [comment]
nice nice
